sonar.organization=trbroyles1
sonar.projectKey=trbroyles1_interruptq

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/__tests__/**,src/test/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=**/__tests__/**,src/test/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/*.d.ts,scripts/**
sonar.css.file.suffixes=.css,.module.css
